BOOTLOADER = atmel-dfu

LTO_ENABLE = yes
COMBO_ENABLE = yes
NKRO_ENABLE = no
TAP_DANCE_ENABLE = yes

VIA_ENABLE = no
CONSOLE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_LOCK_ENABLE = no